### ISSUE TITLE
도장판 메인페이지 UI 구현

### ISSUE THREAD

**Issue by paneiOS** [POLZZAK/POLZZAK-iOS#2]
## Description
도장판 메인페이지의 UI를 Code base로 구현합니다.

## Todo
- [ ] 상단 네비게이션바 RightButton 구현
- [ ] 상단 네비게이션바 하단영역 구현
- [ ] 필터 구현
- [ ] CollectionView(콘텐츠) 구현
- [ ] 도장판 추가하기 버튼 구현

## ETC
- 타입별(보호자/아이) 처리
- UINavigation의 시작점 고민
- 스켈레톤 라이브러리 사용

> 기타 참고사항(URL, Image 등)
- 스켈레톤(https://github.com/JK0369/ExSkeletonView)
---

### ⚠️ Branch naming 참고

`feature/{issue-number}-{feature-name}` 형태입니다

**Comment by paneiOS** [comment]
감사합니다.
