### ISSUE TITLE
도장판화면, 쿠폰함화면 UI 통합 리팩토링

### ISSUE THREAD

**Issue by paneiOS** [POLZZAK/POLZZAK-iOS#20]
## Description

- 메인홈 리팩토링

## Todo

- [ ] 도장판화면, 쿠폰함화면 UI 통합
- [ ] 그래프 그려질때 그려지는 위치가 변경되는 이슈
- [ ] 변경된 폰트 반영

## ETC

> 기타 참고사항(URL, Image 등)

---

### ⚠️ Branch naming 참고

`feature/{issue-number}-{feature-name}` 형태입니다

- feature/20-StampBoardUI
