### ISSUE TITLE
네트워크 모듈 작성

### ISSUE THREAD

**Issue by z3rosmith** [POLZZAK/POLZZAK-iOS#3]
## Description

- URLSession을 이용, Testable 하게 작성
- Interceptor, Adaptor 구현

## Todo

- [x] Testable한 네트워크 모듈 작성
- [x] Adapter, Retrier 구현
- [x] Retrier 테스트를 위해 카카오 로그인 API 작성

## ETC

> 참고사항
> https://ios-development.tistory.com/719

---

### ⚠️ Branch naming 참고

`feature/{issue-number}-{feature-name}` 형태입니다
